# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/atotto/clipboard"
  revision = "5e2c7bddca04488284428a201e4a15615f7a5074"

[[constraint]]
  name = "github.com/bclicn/color"
  revision = "4c02eff8a28c1add99b3b5b238c165056c3bea8e"

[[constraint]]
  name = "github.com/dustin/go-humanize"
  revision = "02af3965c54e8cacf948b97fef38925c4120652c"

[[constraint]]
  name = "github.com/coreos/bbolt"
  version = "v1.3.1-coreos.6"

[[constraint]]
  # branch = "master"
  name = "github.com/mitchellh/go-homedir"
  revision = "b8bc1bf767474819792c23f32d8286a45736f1c6"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[prune]
  go-tests = true
  unused-packages = true
